### ISSUE TITLE
config.json missing the connectionString:"mongodb://localhost/xapi-launch"

### ISSUE THREAD

**Issue by SeemaSP** [adlnet/xapi-launch#11]
I just figured this out when I tried checking out media Types menu and when I tried the **view db records** actions, it gave a the following error:

`Cannot GET /mediaType/`

**Comment by rchadwic** [comment]
Right - This should only be an issue for the single, default "Supports No Media" Media type. It is a hard-coded special case, and therefore has no DB entry. That button in the GUI should just be removed.

**Comment by SeemaSP** [comment]
I have some questions regarding the launch server. I am a nodejs newbie and have been trying to understand your implementation of the launch mechanism. I am a Django developer and I wish to implement the same. But I am unable to understand whether you have used express or node js for this app. Also how does the DAL.js store the launch token and the associated content(course) and user information? Just need some help in understanding the modules of the server.

**Comment by rchadwic** [comment]
Sure, I'll be happy to discuss a bit. I've tried to add a lot of inline comments into the code for the launch part, but much of the boilerplate is not explained. 

We do use both Express and node.js. Think of Express like Django, and node like the Python runtime. One small difference - I think Django has a database layer. Express does not, so we use Mongoose, which adds such a layer over the Mongodb server. 

DAL.js mostly is a big set of convenience functions for things like "Get all users" or "find a launch record by ID". This is mostly wrapping up the Mongoose logic. 

The main file - app.js, created the Express server and sends it to each of the modules in /server/ to have routes attached. These files are generally grouped by their function.

Files.js contains all the logic for uploading a zipped course package.
Admin contains the routes for administrative functions. 
Email.js contains the logic for sending emails out when accounts are created. 
Form.js is a middleware component that generates HTML forms from a description
Media.js contains the logic for the CRUD operations on media objects in the DB. 
MediaType.js does the same for the MediaTypes
Content.js does the same for the content records.

A good and simple example of the general flow of an Express route is on line 395 of Content.js

```
app.get("/content/searchid/:search", function(req, res, next)
    {
        res.locals.pageTitle = "Search All Apps";
        var search = decodeURIComponent(req.params.search);
        var reg = (search);
        DAL.getAllMediaTypes(function(err, types)
        {
            DAL.getContentByKey(reg, function(err, result)
            {
                if (err || !result)
                {
                  ...
                }
                else
                {
                    var results = [result];
                    for (var i in results)
                    {
                        results[i].virtuals.launchKey = results[i]._id;
                        ...
                    }
                    res.locals.results = results;
                    res.render('contentResults', res.locals);
                }
            })
        })
    });
```

Here you can see that we hook up a function to service the route `/content/serachid/:search`. `:search` is sort of like a wildcard - Express will route the request to this function whatever that term is. 

The function uses the value of the `:search` parameter to make some call into the DAL, and render the DB results into the page template called "contentResults". This happens with the `res.render(....)` line. 

That general flow describes the majority of the code - it's mostly boilerplate CRUD stuff for several different data types. All the fun happens in Launch.js, and I've tried to document that extensively. 

Does that help with general app organization?

**Comment by SeemaSP** [comment]
First of all thanks for such a detailed response. I now understand the purpose of some of these .js files. So correct me if I am wrong, but the DAL is like database layer abstracting all the query operations on your models(which is DAL I hope). 

And I have been looking at the launch.js code. You mention something about asynchronous requests which request for a launch token and the same token is given to both requests and so you synchronize this process. 

Since I don't know whether such a thing could happen to say a token generation module in django app, I have planned to implement first a view wherein I generate a token(unique) and give it in response to requests. I have some (ideas)rough code of abstracting the launch token module as a class(django model) and then store the launch token generated with other details like user data and lrs credentials(hard coded for now since I am trying for proof of concept). 

I would like your opinion on whether what I understand of the algorithm so far in what I have described is correct ?( or nearly correct :-))

**Comment by rchadwic** [comment]
Hummm. I'm not sure that I understand your summary ;)

So, when a user clicks the launch button on the launch server , that creates a new record, which is sort of an intention to launch the content. That record has an ID - the launch token. We send that launch token to the user in one of several ways - you can redirect their browser to the content url and include the token in the query string, or just print the token to the screen. 

At some point, the server is expecting something to "initialize" this launch - meaning some system somewhere must pass this token back to the launch server, and part of the "session start" handshake. If the token is valid, and has not already been used, then we return a cookie and configuration data to the caller. The session is marked open, and we create a one time use xAPI endpoint for this session. From here on, the cookie value is necessary to use that one time use endpoint - so only a single system can post statements to this session. If that system chooses to share the cookie somehow, we of course cannot control that. 

Optionally, when the token is sent to the user, it can be encrypted with the public key of the content, so that the user themselves cannot find the token, and thus cannot initiate the session themselves. 

So there are 2 tokens in play - the one used to initiate the session (the launch token) , and one used to control access to an open session (the cookie).

Does that help at all?

**Comment by SeemaSP** [comment]
Yes. It does clear most of the doubts I had. I have started with basic implementation as mentioned in the summary and would soon commit if possible.I wish to continue this discussion on a different thread if that is okay with you. It would help to have a thread like that?

**Comment by rchadwic** [comment]
Sure, I'd be happy. You can also just call me, or GChat me at my work address. Robert.chadwick.ctr@adlnet.gov
