### ISSUE TITLE
Error posting to the LRS https://host:port/xapi/: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by SeemaSP** [adlnet/xapi-launch#13]
I have proxied ADL LRS behind nginx. Now I have set the appropriate LRS endpoint in the config.json and in the user details of any xapi-launch user. But when I am launching the demo.html site, I am getting the following error:

`Error posting to the LRS https://host:port/xapi/: Error: unable to verify the first certificate
`
Because of this, the launch history is updated, but doesn't send this data to LRS.

**Comment by rchadwic** [comment]
That looks like an issue with the SSL cert chain from your Nginx server.  Maybe try running https://www.ssllabs.com/ssltest/ on your endpoint to verify that the cert chain is complete? I've seen issues in the past where Node.js does not come bundled with some root certs that Chrome does, so it's possible that your endpoint appears correct in Chrome but not in Node. Does the string actually say "host:port"? That might be a configuration issue.

**Comment by SeemaSP** [comment]
It doesn't say host:port. It is a valid host listening on port 443. But the certificate here is created using openssl and self signed using tinyCA. So is there no way to configure it to validate such self signed certificated?

**Comment by rchadwic** [comment]
Ah.  There is a sort of a trick to forcing Node.js into accepting a self signed certificate. We won't add a configuration flag, because this is generally a bad idea. If you must get the server to accept your self signed certificate, you can add a line to the beginning of the app.js file. Here's a thread that discusses the issue.

https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
